server:
  port: 6680
  servlet:
    context-path: /api

spring:
  datasource:
    druid:
      # driver-class-name: com.mysql.cj.jdbc.Driver
      # url: jdbc:mysql://47.104.74.122:9301/coalsalecs?useUnicode=yes&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      # username: root
      # password: Dongrun1234@mysqls
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@172.17.0.2:1521/ORCLPDB
      username: coalsale
      password: coalsale
      initial-size: 20
      max-active: 50
      min-idle: 20
      max-wait: 10000
      keep-alive: true
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 1800000
      # validation-query: select 1
      validation-query: select * from dual
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      # remove-abandoned: true
      # remove-abandoned-timeout: 600
      # log-abandoned: true
      filters: stat,wall
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000

logging:
  level:
    # root: DEBUG
    root: INFO

mybatis-plus:
  mapper-locations: classpath*:com/drzyl/**/mapping/*.xml
  configuration:
    jdbc-type-for-null: NULL

proconfig:
  # 会话过期时间 0 代表 365天
  # 从 1 开始是代表毫秒数
  cookies-times-effect-browser: 3600000
  cookies-times-effect-android: 0
  cookies-times-effect-ios: 0
  cookies-times-effect-wechatapp: 0
  authorization-interceptor: true
  http-request-body-decode: false
  http-response-body-encode: false
