DROP TABLE PAR_UPLOAD_FILE;

/*==============================================================*/
/* NAME:<文件信息> TABLE: PAR_UPLOAD_FILE                         */
/*==============================================================*/
CREATE TABLE PAR_UPLOAD_FILE (
  FILE_ID							VARCHAR2(255 BYTE)		VISIBLE	NOT NULL,
  FILE_NAME							VARCHAR2(255 BYTE)		VISIBLE	NOT NULL,
  FILE_URL							VARCHAR2(255 BYTE)		VISIBLE		NULL,
  FILE_TYPE							VARCHAR2(255 BYTE)		VISIBLE		NULL,
  FILE_SIZE							VARCHAR2(255 BYTE)		VISIBLE		NULL,
  FILE_SUFFIX						VARCHAR2(255 BYTE)		VISIBLE		NULL, 
  MODULE							VARCHAR2(255 BYTE)		VISIBLE		NULL, 
  MODULE_HASH						VARCHAR2(255 BYTE)		VISIBLE		NULL, 
  REMARK							VARCHAR2(4000 BYTE)		VISIBLE		NULL,
  VERSIONS							NUMBER(11)				VISIBLE	NOT NULL,
  CREATE_ID							VARCHAR2(255 BYTE)		VISIBLE	NOT NULL,
  CREATE_NAME						VARCHAR2(255 BYTE)		VISIBLE	NOT NULL,
  CREATE_ORG						VARCHAR2(255 BYTE)		VISIBLE		NULL,
  CREATE_TIMES						NUMBER(20)				VISIBLE	NOT NULL,
  DEL_FLAG							VARCHAR2(255 BYTE)		VISIBLE		NULL, 
  PRIMARY KEY ( FILE_ID )
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT 
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON TABLE "PAR_UPLOAD_FILE" IS '上传文件';
COMMENT ON COLUMN "PAR_UPLOAD_FILE"."FILE_ID" IS 'ID';
COMMENT ON COLUMN "PAR_UPLOAD_FILE"."FILE_NAME" IS '文件名称';
COMMENT ON COLUMN "PAR_UPLOAD_FILE"."FILE_URL" IS '文件路径';
COMMENT ON COLUMN "PAR_UPLOAD_FILE"."FILE_TYPE" IS '文件类型';
COMMENT ON COLUMN "PAR_UPLOAD_FILE"."FILE_SIZE" IS '文件大小(单位B)';
COMMENT ON COLUMN "PAR_UPLOAD_FILE"."FILE_SUFFIX" IS '文件后缀';
COMMENT ON COLUMN "PAR_UPLOAD_FILE"."MODULE" IS '文件来源模块';
COMMENT ON COLUMN "PAR_UPLOAD_FILE"."MODULE_HASH" IS '来源HASH';
COMMENT ON COLUMN "PAR_UPLOAD_FILE"."REMARK" IS '备注';
COMMENT ON COLUMN "PAR_UPLOAD_FILE"."VERSIONS" IS '版本号';
COMMENT ON COLUMN "PAR_UPLOAD_FILE"."CREATE_ID" IS '创建人账号';
COMMENT ON COLUMN "PAR_UPLOAD_FILE"."CREATE_NAME" IS '创建人名称';
COMMENT ON COLUMN "PAR_UPLOAD_FILE"."CREATE_TIMES" IS '创建时间';
COMMENT ON COLUMN "PAR_UPLOAD_FILE"."CREATE_ORG" IS '创建机构';
COMMENT ON COLUMN "PAR_UPLOAD_FILE"."DEL_FLAG" IS '逻辑删除0=删除,1=显示';
