DROP TABLE SYS_SEND_SMS_LOG;
CREATE TABLE SYS_SEND_SMS_LOG (
	ID 					VARCHAR2(255),
	PHONE 				VARCHAR2(255),
	TEMPLATECODE 		VARCHAR2(255),
	CONTEXT 			VARCHAR2(4000),
	MESSAGE 			VARCHAR2(255),
	CODE 				VARCHAR2(255),
	REQUESTID 			VARCHAR2(255),
	BIZID 				VARCHAR2(255),
	CREATE_ID 			VARCHAR2(255),
	CREATE_NAME 		VARCHAR2(255),
	CREATE_ORG 			VARCHAR2(255),
	CREATE_TIMES 		NUMBER,
	CONSTRAINT SYS_SEND_SMS_LOG_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE SYS_SEND_SMS_LOG IS '发送信息记录';
COMMENT ON COLUMN SYS_SEND_SMS_LOG.ID IS 'ID';
COMMENT ON COLUMN SYS_SEND_SMS_LOG.PHONE IS '接受手机号';
COMMENT ON COLUMN SYS_SEND_SMS_LOG.TEMPLATECODE IS '短信模板';
COMMENT ON COLUMN SYS_SEND_SMS_LOG.CONTEXT IS '发送内容';
COMMENT ON COLUMN SYS_SEND_SMS_LOG.MESSAGE IS '返回消息';
COMMENT ON COLUMN SYS_SEND_SMS_LOG.CODE IS '返回代码:ok表示成功';
COMMENT ON COLUMN SYS_SEND_SMS_LOG.REQUESTID IS '查询请求ID';
COMMENT ON COLUMN SYS_SEND_SMS_LOG.BIZID IS '查询回执ID';
COMMENT ON COLUMN SYS_SEND_SMS_LOG.CREATE_ID IS '创建ID';
COMMENT ON COLUMN SYS_SEND_SMS_LOG.CREATE_NAME IS '创建人姓名';
COMMENT ON COLUMN SYS_SEND_SMS_LOG.CREATE_ORG IS '创建机构';
COMMENT ON COLUMN SYS_SEND_SMS_LOG.CREATE_TIMES IS '创建时间';

