DROP TABLE SYS_SMS_SECURITY_CODE;
/*==============================================================*/
/* NAME:<安全验证码> TABLE: SYS_SECURITY_CODE                         */
/*==============================================================*/
-- DROP TABLE SYS_SMS_SECURITY_CODE;
CREATE TABLE SYS_SMS_SECURITY_CODE (
  ID								VARCHAR2(255 BYTE)		VISIBLE	NOT NULL,
  SECURITY_CODE						VARCHAR2(255 BYTE)		VISIBLE	NOT NULL,
  PHONE_NUMBER						VARCHAR2(255 BYTE)		VISIBLE	NOT NULL,
  ACTION							VARCHAR2(255 BYTE)		VISIBLE	NOT NULL,
  CREATE_TIMES						NUMBER(20)				VISIBLE	NOT NULL,
  PRIMARY KEY ( ID ),
  UNIQUE ( SECURITY_CODE )
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT 
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON TABLE "SYS_SMS_SECURITY_CODE" IS '短信验证码';
COMMENT ON COLUMN "SYS_SMS_SECURITY_CODE"."ID" IS 'ID';
COMMENT ON COLUMN "SYS_SMS_SECURITY_CODE"."PHONE_NUMBER" IS '手机号';
COMMENT ON COLUMN "SYS_SMS_SECURITY_CODE"."SECURITY_CODE" IS '验证码';
COMMENT ON COLUMN "SYS_SMS_SECURITY_CODE"."ACTION" IS '行为';
COMMENT ON COLUMN "SYS_SMS_SECURITY_CODE"."CREATE_TIMES" IS '创建时间';
